### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
This improves performance in browsers that try to auto correct with text area.  While I was in the code I decided to give it a once over and also add pretty print.  Thank you for this very helpful library!  I use it often.

### CODE REVIEW

**Comment by gavinr** [comment]
Thanks for the PR, Robert! I will review within a few days.

**Comment by robertleeplummerjr** [comment]
Awesome!

**Comment by gavinr** [comment]
Thanks again! It's not live up on http://csv.togeojson.com yet - I'm working on moving to GitHub gh-pages hosting (see #10)

**Comment by robertleeplummerjr** [comment]
A fire starts with but a match.  Strike on!

**Pull request merged**
